# config/traintrack.toml
# This file provides configuration settings for the TrainTrack module.

# Example: Define rules for function naming conventions.
# These values can be accessed by your Rust code to enforce style.

[naming_conventions]
# List of recognized verbs for function names (e.g., for TT015)
function_verbs = [
    "add",
    "analyze",
    "append",
    "assert",
    "audit",
    "cache",
    "calculate",
    "cancel",
    "check",
    "configure",
    "convert",
    "create",
    "decode",
    "delete",
    "detect",
    "dispatch",
    "encode",
    "estimate",
    "execute",
    "fetch",
    "filter",
    "format",
    "get",
    "group",
    "inspect",
    "launch",
    "listen",
    "load",
    "log",
    "map",
    "merge",
    "normalize",
    "notify",
    "pause",
    "predict",
    "print",
    "prompt",
    "purge",
    "query",
    "read",
    "reduce",
    "respond",
    "resume",
    "run",
    "sanitize",
    "save",
    "schedule",
    "set",
    "simulate",
    "sort",
    "split",
    "store",
    "sync",
    "tag",
    "test",
    "track",
    "update",
    "validate",
    "verify",
    "warn",
    "watch",
    "wreck"
]

# List of recognized adjectives for function names (e.g., for TT018)
function_adjectives = [
    "active",
    "asynchronous",
    "available",
    "binary",
    "cached",
    "clean",
    "compiled",
    "compressed",
    "concurrent",
    "configured",
    "connected",
    "constant",
    "current",
    "custom",
    "default",
    "deprecated",
    "dirty",
    "distributed",
    "dynamic",
    "enabled",
    "encrypted",
    "ephemeral",
    "exclusive",
    "expected",
    "expired",
    "external",
    "faulty",
    "global",
    "idle",
    "immutable",
    "internal",
    "invalid",
    "locked",
    "local",
    "manual",
    "maximum",
    "minimum",
    "missing",
    "offline",
    "online",
    "optional",
    "parallel",
    "pending",
    "primary",
    "readable",
    "remote",
    "running",
    "secondary",
    "secure",
    "serial",
    "shared",
    "signed",
    "stale",
    "static",
    "temporary",
    "trusted",
    "unique",
    "unlocked",
    "unsaved",
    "valid",
    "volatile",
    "writable"
]

# List of recognized nouns for function names (e.g., for TT016, TT019)
function_nouns = [
    "adapter",
    "address",
    "archive",
    "argument",
    "artifact",
    "attribute",
    "bit",
    "block",
    "byte",
    "command",
    "component",
    "constant",
    "cursor",
    "dataset",
    "event",
    "frame",
    "gateway",
    "graph",
    "heap",
    "index",
    "iterator",
    "message",
    "method",
    "module",
    "namespace",
    "node",
    "opcode",
    "package",
    "path",
    "pipeline",
    "port",
    "profile",
    "queue",
    "range",
    "region",
    "registry",
    "repository",
    "response",
    "row",
    "schema",
    "service",
    "signal",
    "socket",
    "span",
    "stream",
    "table",
    "tag",
    "transaction",
    "type",
    "unit",
    "view",
    "workspace"
]

# Enforce camelCase instead of snake_case for function names
# force_camel_case = false
